# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190209_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='piblished_date',
            new_name='published_date',
        ),
    ]
